[package]
name = "aptosverse"
version = "1.0.0"
authors = []

[addresses]
module_addr = "_"

[dependencies]
AptosFramework = { local = "C:/Users/youss/OneDrive/Bureau/aptos-core-main/aptos-core-main/aptos-move/framework/aptos-framework" , rev="testnet" }
AptosTokenObjects = { local = "C:/Users/youss/OneDrive/Bureau/aptos-core-main/aptos-core-main/aptos-move/framework/aptos-token-objects", rev = "testnet" }

[dev-dependencies]
